spring.application.name=SmartExpenseTracker

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database = Expense

server.port=8080
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
